const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id eros porta, pretium eros ac, condimentum tellus. Vivamus vulputate ex nec risus dapibus, ut malesuada magna viverra. Suspendisse sem eros, mattis ut mauris sed, aliquam rutrum nulla. Mauris eu dictum nisl. Aliquam vitae lacus sem. Etiam dictum risus velit, ut viverra diam vehicula id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at porttitor sem, in consectetur enim. Proin lobortis nisi fermentum, convallis metus vel, auctor odio.

Phasellus facilisis diam massa, ut ullamcorper odio accumsan id. Nulla tempor ut neque eget convallis. Integer quis tellus ut felis dictum mattis ac vitae neque. Donec fermentum ultricies sapien, a egestas diam lobortis vitae. Etiam orci ipsum, egestas sed gravida sit amet, condimentum eget tortor. Nulla non tincidunt ante. Proin mollis lectus libero, ac faucibus nibh placerat nec.

Mauris ac justo commodo, ornare dolor nec, dignissim velit. Morbi efficitur leo sit amet elit faucibus, vitae venenatis odio pharetra. Mauris ac consequat tortor, luctus gravida lacus. Nunc faucibus lectus non quam ultrices, vel condimentum ipsum aliquet. Phasellus vel enim purus. Nulla tincidunt, turpis volutpat elementum maximus, lacus dolor consequat nunc, quis efficitur augue nisl id augue. Maecenas imperdiet ipsum eu lobortis aliquet. Etiam auctor magna eu sem pulvinar, et blandit dolor elementum. Mauris a elementum magna.

Nunc sagittis est a tempor mattis. Etiam euismod luctus lectus ac semper. Morbi sed suscipit urna, vitae interdum ex. Suspendisse venenatis lorem eu dolor elementum, et rhoncus justo ullamcorper. Integer turpis nulla, consequat at dictum vitae, ullamcorper efficitur libero. Morbi fringilla commodo orci a malesuada. Quisque id pharetra ipsum. Etiam ac dui gravida est elementum consequat. In vitae sapien felis.

Integer aliquam est at congue sagittis. Vivamus at mollis ante, rutrum finibus quam. Aenean sollicitudin, tellus eu vehicula sodales, nunc elit semper lectus, ut tempus nunc enim in quam. In commodo tempor nunc, ac iaculis nisl porta at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent auctor nunc nulla, eu ultricies felis eleifend ac. Etiam bibendum accumsan elit. Aliquam erat volutpat. Suspendisse tincidunt nibh vitae ante scelerisque tempor. Sed id metus neque. Pellentesque id odio at ipsum molestie pulvinar in vitae sem. Suspendisse porta eleifend tincidunt. Praesent ornare tincidunt elit ac semper. Phasellus vitae tincidunt erat. Morbi malesuada gravida elementum. Suspendisse eget lorem ut neque bibendum tempus.
`;

export default loremIpsum;
